version: "2"
services:
  cassandra:
    image: library/cassandra:2.1.21
    restart: unless-stopped
    ports:
      - 7000:7000
      - 9042:9042
      - 9160:9160
      - 9142:9142
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
